# Generated by Django 5.2.4 on 2025-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webappscanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('target', models.URLField()),
                ('alert', models.CharField(max_length=255)),
                ('risk', models.CharField(max_length=50)),
                ('confidence', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.TextField()),
                ('param', models.CharField(blank=True, max_length=255, null=True)),
                ('cweid', models.CharField(blank=True, max_length=50, null=True)),
                ('wascid', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MentalHealthRecord',
        ),
    ]
