# Generated by Django 5.2.4 on 2025-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webappscanner', '0002_webappscanresult_delete_mentalhealthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappscanresult',
            name='alert',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webappscanresult',
            name='confidence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webappscanresult',
            name='cweid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webappscanresult',
            name='risk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webappscanresult',
            name='scan_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webappscanresult',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webappscanresult',
            name='wascid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
