# Generated by Django 5.2.4 on 2025-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webappscanner', '0003_alter_webappscanresult_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappscanresult',
            name='scan_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webappscanresult',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='webappscanresult',
            index=models.Index(fields=['scan_id'], name='webappscann_scan_id_216ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='webappscanresult',
            index=models.Index(fields=['-created_at'], name='webappscann_created_f3aeff_idx'),
        ),
    ]
