# Generated by Django 5.2.4 on 2025-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiscanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiscan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apiscan',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apiscan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apiscan',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
