# Generated by Django 5.2.4 on 2025-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('tls_version', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_report', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
