# Generated by Django 5.2.4 on 2025-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkscanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkscan',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='ip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='ports',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='networkscan',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
